# Generated by Django 6.0.6 on 2026-06-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='রোগীর নাম')),
                ('phone', models.CharField(max_length=20, verbose_name='ফোন নম্বর')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('age', models.PositiveIntegerField(verbose_name='বয়স')),
                ('problem', models.TextField(verbose_name='সমস্যার বিবরণ')),
                ('chamber', models.CharField(max_length=200, verbose_name='চেম্বার')),
                ('preferred_date', models.DateField(verbose_name='পছন্দের তারিখ')),
                ('preferred_time', models.CharField(max_length=50, verbose_name='পছন্দের সময়')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
