# Generated by Django 6.0.6 on 2026-06-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('description_bn', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('youtube_id', models.CharField(help_text='YouTube Video ID (e.g. VeAJ9U5LBSA)', max_length=50)),
                ('category_bn', models.CharField(max_length=100)),
                ('category_en', models.CharField(max_length=100)),
                ('duration', models.CharField(default='0:00', max_length=10)),
                ('views', models.CharField(default='0', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
