# Generated by Django 6.0.6 on 2026-06-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('category', models.CharField(choices=[('conference', 'Conference'), ('award', 'Award'), ('chamber', 'Chamber'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=50),
        ),
    ]
