# Generated by Django 6.0.6 on 2026-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('subtitle_bn', models.CharField(max_length=200)),
                ('subtitle_en', models.CharField(max_length=200)),
                ('address_bn', models.TextField()),
                ('address_en', models.TextField()),
                ('time_bn', models.CharField(max_length=100)),
                ('time_en', models.CharField(max_length=100)),
                ('days_bn', models.CharField(max_length=100)),
                ('days_en', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('map_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
