# Generated by Django 6.0.6 on 2026-06-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('summary_bn', models.TextField()),
                ('summary_en', models.TextField()),
                ('content_bn', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('category_bn', models.CharField(max_length=100)),
                ('category_en', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('date', models.DateField()),
                ('read_time', models.PositiveIntegerField(default=5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
