# Generated by Django 6.0.6 on 2026-06-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-trophy', max_length=100)),
                ('title_bn', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('organization_bn', models.CharField(max_length=200)),
                ('organization_en', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
