# Generated by Django 6.0.6 on 2026-06-10 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=200, verbose_name='নাম (বাংলা)')),
                ('name_en', models.CharField(max_length=200, verbose_name='নাম (ইংরেজি)')),
                ('title_bn', models.CharField(max_length=300, verbose_name='পদবি (বাংলা)')),
                ('title_en', models.CharField(max_length=300, verbose_name='পদবি (ইংরেজি)')),
                ('speciality_bn', models.CharField(max_length=200)),
                ('speciality_en', models.CharField(max_length=200)),
                ('hospital_bn', models.CharField(max_length=300)),
                ('hospital_en', models.CharField(max_length=300)),
                ('address_bn', models.TextField()),
                ('address_en', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('patients_count', models.PositiveIntegerField(default=0)),
                ('publications_count', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor/')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution_bn', models.CharField(max_length=200)),
                ('institution_en', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='doctor.doctorprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
