# Generated by Django 6.0.6 on 2026-06-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('summary_bn', models.TextField()),
                ('summary_en', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
